docs(api protection): add java sample code
logto-io/docs pull request #87
Opened 2022-06-29 12:53 UTC by simeng-li

add java sample code and create some fragments to reduce line size. 

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/36393111/176440980-32a39bdf-3107-438a-89ef-c1cc66fcb17c.png">

<img width="1593" alt="imag@logto-io/eng rc="https://user-images.githubusercontent.com/36393111/176440914-e099783d-86a5-40f4-83aa-e1ffa1b67c41.png">

@eng

2022-06-29 14:33 UTC, IceHe requested changes
There are some tabs in the java code block.
Remove them and correct the indents.

2022-06-29 14:33 UTC, IceHe commented on docs/docs/recipes/protect-your-api/fragments/_token_extract.mdx
> +	protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
```suggestion
  protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
```

2022-06-29 14:33 UTC, IceHe commented on docs/docs/recipes/protect-your-api/fragments/_token_validation.mdx
> +	<version>0.9.1</version>
```suggestion
  <artifactId>jjwt</artifactId>
  <version>0.9.1</version>
```

2022-06-29 14:33 UTC, IceHe commented on docs/docs/recipes/protect-your-api/fragments/_token_validation.mdx
> +I.e., Checkout [org.springframework.security.oauth2.jwt](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/jwt/package-summary.html), if you use the Spr
```suggestion
I.e., checkout [org.springframework.security.oauth2.jwt](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/oauth2/jwt/package-summary.html), if you use Spring Framework.
```

2022-06-30 02:35 UTC, simeng-li commented
@IceHe updated PTAL

2022-07-05 09:14 UTC, merged